### ISSUE TITLE
Failed to install extension

### ISSUE THREAD

**Issue by orballo** [nefrob/vscode-just#5]
Hi,

I noticed that you just released this extension, but when I was trying to install it I got this error (just in case you are not aware):

```
Can't install release version of 'nefrob.vscode-just-syntax' extension because it has no release version.
```

Cheers!

EDIT: Oh, nevermind. I just noticed there is an option to install the pre-release version 😅

**Comment by nefrob** [comment]
Yeah, I left it in pre-release to test things over the coming weeks. I will add a line to the readme calling this out for now.

**Comment by m1rm** [comment]
also tried installing today, since casey/just also recommends this extension. Eagerly waiting for it to be ready <3

**Comment by nefrob** [comment]
@m1rm the latest version is out of pre-release if you can try to install that version.

<img width="335" alt="Screenshot 2024-05-17 at 8 13 28 AM" src="https://github.com/nefrob/vscode-just/assets/25070989/e28ae64e-03b0-47bf-ab90-a85b9bbc8d82">

<img width="604" alt="Screenshot 2024-05-17 at 8 12 32 AM" src="https://github.com/nefrob/vscode-just/assets/25070989/2e1c2cef-1676-497f-8568-53189d5d596c">

If this still doesn't work for you please provide your OS, vscode version and the extension version.

**Comment by m1rm** [comment]
thanks for your fast reply! So, the issue is, that VSCode's plugin search does (sadly) not show your plugin (I searched for name, name with publisher). 

So I tried to install it via the CLI:

`code --install-extension nefrob.vscode-just-syntax `

which gives me:
![Bildschirmfoto vom 2024-05-17 16-42-04](https://github.com/nefrob/vscode-just/assets/74644501/a044d256-526c-4a49-99a8-4bfe0bf2660a)

**Comment by nefrob** [comment]
Hmm can you check if you are using a community / open source build of vscode instead of an official build? If so, the extension might also need to be published to https://open-vsx.org/. 

Another option is to add the `.vsix` file to the release artifacts so people can install a release without going through the official vscode marketplace.

**Comment by m1rm** [comment]
interesting. 

Since I am on Arch Linux, I used the package provided via the extra repository: https://www.archlinux.de/packages/extra/x86_64/code

**Comment by nefrob** [comment]
@m1rm now published on open vsx here: https://open-vsx.org/extension/nefrob/vscode-just-syntax.
